;4.6
(define (eval46 exp env)
    (cond ((let? exp) (eval46 (let-combination exp) env))))
(define (let-defn exp) (cadr exp))
(define (let-body exp) (cddr exp))
(define (let-combination exp env)
    (let ((defn (let-defn exp))
          (body (let-body exp)))
        (let ((vars (map car defn))
              (exps (map cadr defn)))
            (cons (make-lambda vars body)
                  exps))))