;4.21
;a)这个函数就是多套了一层lambda而将函数隐式地绑定为fact\ft
((lambda (n)
    ((lambda (fact) (fact fact n 1 1))
        (lambda (ft k one two)
            (cond ((= k 1) one)
                  ((= k 2) two)
                  (else (ft ft (- k 1) two (+ two one)))))))
6)
;b)
(define (f x)
    ((lambda (even? odd?)
        (even? even? odd? x))
     (lambda (ev? od? n)
        (if (= n 0) #t (od? ev? od? (- n 1))))
     (lambda (ev? od? n)
        (if (= n 0) #f (ev? ev? od? (- n 1))))))